export const profileData = {
  name: "Oscar Senior",
  location: "United Kingdom",
  bio: "Penetration tester and red team operator. Specialized in offensive security, command & control operations, and post-exploitation techniques. Completed Red Teaming, Jr Penetration Tester, and Pre Security pathways on TryHackMe.",
  status: "ACTIVE",
  
  tryhackme: {
    username: "Oscar.Senior",
    profileUrl: "https://tryhackme.com/p/Oscar.Senior",
    rank: "#45,295",
    tier: "MASTER",
    tierBadge: "0xB",
    rooms: 156,
    badges: 22,
    streak: 0,
  },

  pathways: [
    {
      name: "Red Teaming",
      completed: "Dec 18, 2024",
      icon: "Zap",
    },
    {
      name: "Jr Penetration Tester",
      completed: "Oct 28, 2024",
      icon: "Shield",
    },
    {
      name: "Pre Security",
      completed: "Sep 30, 2024",
      icon: "Lock",
    },
  ],

  achievements: [
    // Learning Path Completions
    {
      name: "Red Teaming",
      fullName: "Red Teaming Pathway Complete",
      issuer: "TryHackMe",
      icon: "Zap",
      earned: "Dec 18, 2024",
      rarity: "epic",
      percentage: "1%",
      category: "Learning Paths",
    },
    {
      name: "Jr Penetration Tester",
      fullName: "Junior Penetration Tester Pathway Complete",
      issuer: "TryHackMe",
      icon: "Shield",
      earned: "Oct 28, 2024",
      rarity: "epic",
      percentage: "2%",
      category: "Learning Paths",
    },
    {
      name: "Pre Security",
      fullName: "Pre Security Pathway Complete",
      issuer: "TryHackMe",
      icon: "Lock",
      earned: "Sep 30, 2024",
      rarity: "epic",
      percentage: "3%",
      category: "Learning Paths",
    },
    // Common Badges
    {
      name: "First Four",
      fullName: "Completing four rooms in your first week",
      issuer: "TryHackMe",
      rarity: "common",
      percentage: "24.5%",
      category: "Foundations",
    },
    {
      name: "Networking Nerd",
      fullName: "Completing the Network Fundamentals module",
      issuer: "TryHackMe",
      rarity: "common",
      percentage: "17.8%",
      category: "Foundations",
    },
    {
      name: "Webbed",
      fullName: "Understands how the world wide web works",
      issuer: "TryHackMe",
      rarity: "common",
      percentage: "23.9%",
      category: "Foundations",
    },
    {
      name: "World Wide Web",
      fullName: "Completing the How The Web Works module",
      issuer: "TryHackMe",
      rarity: "common",
      percentage: "21.2%",
      category: "Foundations",
    },
    {
      name: "cat linux.txt",
      fullName: "Being competent in Linux",
      issuer: "TryHackMe",
      rarity: "common",
      percentage: "29.8%",
      category: "Foundations",
    },
    {
      name: "Blue",
      fullName: "Hacking into Windows via EternalBlue",
      issuer: "TryHackMe",
      rarity: "common",
      percentage: "11%",
      category: "Exploitation",
    },
    // Rare Badges - Offensive Security
    {
      name: "Hash Cracker",
      fullName: "Cracking all those hashes",
      issuer: "TryHackMe",
      rarity: "rare",
      percentage: "4.8%",
      category: "Offensive Security",
    },
    {
      name: "Pentesting Principles",
      fullName: "Completing the Introduction to Pentesting module",
      issuer: "TryHackMe",
      rarity: "rare",
      percentage: "10%",
      category: "Offensive Security",
    },
    {
      name: "Intro to Web Hacking",
      fullName: "Completing the Introduction to Web Hacking module",
      issuer: "TryHackMe",
      rarity: "rare",
      percentage: "6.1%",
      category: "Offensive Security",
    },
    {
      name: "Burp'ed",
      fullName: "Completing the Burp Suite module",
      issuer: "TryHackMe",
      rarity: "rare",
      percentage: "5.4%",
      category: "Offensive Security",
    },
    {
      name: "OWASP Top 10",
      fullName: "Understanding every OWASP vulnerability",
      issuer: "TryHackMe",
      rarity: "rare",
      percentage: "9.7%",
      category: "Offensive Security",
    },
    {
      name: "Metasploitable",
      fullName: "Contains the knowledge to use Metasploit",
      issuer: "TryHackMe",
      rarity: "rare",
      percentage: "9.6%",
      category: "Offensive Security",
    },
    {
      name: "Authentication Striker",
      fullName: "Used the Hammer to bypass authentication",
      issuer: "TryHackMe",
      rarity: "rare",
      percentage: "1.4%",
      category: "Offensive Security",
    },
    {
      name: "SQL Slayer",
      fullName: "Conquered Advanced SQL Injection",
      issuer: "TryHackMe",
      rarity: "rare",
      percentage: "1.7%",
      category: "Offensive Security",
    },
    {
      name: "System Sniffer",
      fullName: "Completed the File Path traversal room",
      issuer: "TryHackMe",
      rarity: "rare",
      percentage: "1.1%",
      category: "Offensive Security",
    },
    // Advanced & Rare Badges
    {
      name: "Cyber Ready",
      fullName: "Understanding impact of training on teams",
      issuer: "TryHackMe",
      rarity: "rare",
      percentage: "7.7%",
      category: "Advanced",
    },
    {
      name: "ADversary",
      fullName: "Completing all Active Directory networks",
      issuer: "TryHackMe",
      rarity: "rare",
      percentage: "1%",
      category: "Advanced",
    },
    {
      name: "Handle the Disgruntled",
      fullName: "Finishing the Disgruntled challenge",
      issuer: "TryHackMe",
      rarity: "rare",
      percentage: "1.1%",
      category: "Advanced",
    },
    {
      name: "Logging Legend",
      fullName: "Completed the Log Analysis room",
      issuer: "TryHackMe",
      rarity: "rare",
      percentage: "2.4%",
      category: "Advanced",
    },
    {
      name: "Skilled Navigator",
      fullName: "Finishing the Eviction challenge",
      issuer: "TryHackMe",
      rarity: "rare",
      percentage: "5.1%",
      category: "Advanced",
    },
    {
      name: "Security Engineer Intro",
      fullName: "Completed the Security Engineer Intro room",
      issuer: "TryHackMe",
      rarity: "rare",
      percentage: "5.7%",
      category: "Advanced",
    },
    // Epic Badges
    {
      name: "ELKsquisite",
      fullName: "Completed the Slingshot challenge",
      issuer: "TryHackMe",
      rarity: "epic",
      percentage: "0.8%",
      category: "Elite",
    },
  ],

  skills: {
    "Offensive Security": [
      "Penetration Testing",
      "Red Team Operations",
      "Exploit Development",
      "Social Engineering",
    ],
    "Post-Exploitation": [
      "C2 Operations",
      "Lateral Movement",
      "Privilege Escalation",
      "Evasion Techniques",
      "Persistence Mechanisms",
      "Data Exfiltration",
    ],
    "Systems & Infrastructure": [
      "Linux Security",
      "Windows Security",
      "Active Directory",
      "Network Reconnaissance",
      "Vulnerability Assessment",
    ],
    "Core Technical": [
      "Bash/Shell Scripting",
      "Python",
      "HTTP/DNS Protocols",
      "Network Fundamentals",
      "Web Application Security",
      "Reverse Engineering",
    ],
  },

  capabilities: [
    "Active Network Reconnaissance & Mapping",
    "Vulnerability Discovery & Exploitation",
    "Post-Exploitation & Persistence",
    "Lateral Movement & Privilege Escalation",
    "Command & Control Infrastructure Setup",
    "Evasion & Anti-Forensics Techniques",
    "Red Team Campaign Planning",
    "Security Assessment & Reporting",
  ],

  sections: [
    { number: "01", name: "PROFILE", id: "bio" },
    { number: "02", name: "CAPABILITIES", id: "arsenal" },
    { number: "03", name: "CREDENTIALS", id: "achievements" },
  ],
};
